Remove zuul config
To import the repo into openstack the zuul config seems to need to
be removed:

ERROR: Found .zuul.yaml on branch origin/master
  Remove any zuul config files before import.